#!/usr/bin/env python3
"""
gen_embedded_assets.py — embed shader and BGM .MOD files into C++ source.

Usage: python gen_embedded_assets.py <output_dir> <shaders_dir> <bgm_mod_dir>

Generates:
  <output_dir>/embedded_assets.hpp
  <output_dir>/embedded_assets.cpp
"""

import sys, os, re

def c_ident(name: str) -> str:
    """Convert a filename like 'bloom_blur.fs' to a valid C identifier."""
    return re.sub(r'[^A-Za-z0-9_]', '_', name)

def write_header(hpp_path: str, shader_names: list, mod_names: list):
    with open(hpp_path, 'w', newline='\n', encoding='utf-8') as f:
        f.write("// AUTO-GENERATED by cmake/gen_embedded_assets.py — do not edit\n")
        f.write("#pragma once\n")
        f.write("#include <cstddef>\n\n")

        f.write("// ── GLSL shaders (null-terminated strings) ─────────────────────────────\n")
        for name in shader_names:
            ident = c_ident(name)
            f.write(f"extern const char g_shader_{ident}[];\n")
        f.write("\n")

        f.write("// ── Embedded BGM modules ────────────────────────────────────────────────\n")
        f.write("struct EmbeddedMod {\n")
        f.write("    const char*          name;  // filename, e.g. \"CLASS01.MOD\"\n")
        f.write("    const unsigned char* data;\n")
        f.write("    std::size_t          size;\n")
        f.write("};\n\n")
        f.write("extern const EmbeddedMod g_bgm_mods[];\n")
        f.write("extern const int         g_bgm_mod_count;\n")

def write_source(cpp_path: str, shaders_dir: str, shader_names: list,
                 bgm_dir: str, mod_names: list):
    with open(cpp_path, 'w', newline='\n', encoding='utf-8') as f:
        f.write("// AUTO-GENERATED by cmake/gen_embedded_assets.py — do not edit\n")
        f.write("#include \"embedded_assets.hpp\"\n\n")

        # ── Shaders ────────────────────────────────────────────────────────────
        f.write("// ── GLSL shaders ────────────────────────────────────────────────────────\n")
        for name in shader_names:
            path = os.path.join(shaders_dir, name)
            with open(path, 'r', encoding='utf-8', errors='replace') as sf:
                src = sf.read()
            # Use a custom delimiter that is extremely unlikely to appear in GLSL
            delim = "SZGLSL_EMBED"
            # Sanity-check the source doesn't contain our delimiter
            if delim in src:
                delim = "SZGLSL_EMBED_ALT"
            ident = c_ident(name)
            f.write(f"const char g_shader_{ident}[] = R\"{delim}(\n")
            f.write(src)
            if not src.endswith('\n'):
                f.write('\n')
            f.write(f"){delim}\";\n\n")

        # ── BGM MOD data ───────────────────────────────────────────────────────
        f.write("// ── BGM MOD binary data ─────────────────────────────────────────────────\n")
        for name in mod_names:
            path = os.path.join(bgm_dir, name)
            with open(path, 'rb') as bf:
                data = bf.read()
            ident = c_ident(name)
            f.write(f"static const unsigned char bgm_{ident}_data[] = {{\n")
            # Emit 16 bytes per line
            for i in range(0, len(data), 16):
                chunk = data[i:i+16]
                line = ','.join(f'0x{b:02x}' for b in chunk) + ','
                f.write(f"    {line}\n")
            f.write("};\n\n")

        # ── Table ──────────────────────────────────────────────────────────────
        f.write("// ── MOD table ───────────────────────────────────────────────────────────\n")
        f.write("const EmbeddedMod g_bgm_mods[] = {\n")
        for name in mod_names:
            ident = c_ident(name)
            f.write(f'    {{ "{name}", bgm_{ident}_data, sizeof(bgm_{ident}_data) }},\n')
        f.write("};\n\n")
        f.write(f"const int g_bgm_mod_count = {len(mod_names)};\n")

def main():
    if len(sys.argv) != 4:
        print(f"Usage: {sys.argv[0]} <output_dir> <shaders_dir> <bgm_mod_dir>",
              file=sys.stderr)
        sys.exit(1)

    out_dir    = sys.argv[1]
    shaders_dir = sys.argv[2]
    bgm_dir    = sys.argv[3]

    os.makedirs(out_dir, exist_ok=True)

    # Collect shader files (alphabetical, stable order)
    shader_exts = {'.fs', '.vs', '.glsl'}
    shader_names = sorted(
        f for f in os.listdir(shaders_dir)
        if os.path.splitext(f)[1].lower() in shader_exts
    )

    # Collect MOD files (alphabetical, stable order)
    mod_exts = {'.mod', '.xm', '.s3m', '.it'}
    mod_names = sorted(
        f for f in os.listdir(bgm_dir)
        if os.path.splitext(f)[1].lower() in mod_exts
    )

    hpp_path = os.path.join(out_dir, "embedded_assets.hpp")
    cpp_path = os.path.join(out_dir, "embedded_assets.cpp")

    write_header(hpp_path, shader_names, mod_names)
    write_source(cpp_path, shaders_dir, shader_names, bgm_dir, mod_names)

    print(f"[gen_embedded_assets] {len(shader_names)} shaders + {len(mod_names)} MOD files -> {out_dir}")

if __name__ == "__main__":
    main()

